language: minimal
os: osx

addons:
  homebrew:
    packages: 
    - gtk+
    - create-dmg
    update: true

install: ./install-dependencies.sh

script: ./build-app.sh

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: O2Zhrh4XVSFrC8VZZEmsXPoc3N31jhAryOv+J0EyfgDfRH2aIu91GeyVuFMytFBTI1zJ9J4jmQmcP527tpp9vTm53bPPnsfG46lxGjgnQFz8cGtSEq1WdrWcmqhPiDKc/JOM3Pk37z8o69DC2B7XxoObRl+00TiRY93kBkrlQH/ahnu9M6RPrFVqtXfSsrbK+LteoyKd6JKo4pridKkn3juRUk6w38Q3u87V6joH+FCv4mV4okBkwBvlgI/0qQsWJtmdI2faUAareWL5hDAKPYWPoQdJBZz7uTOIs0lPiF91c2r+fXG/GP1Wpsu7JVlAvgG9mSt9OVi4WGxlja6Nn6Fxkd/UeXzpGFs5yKjKDkzYVpNpZN5mcCxeg7Psh1vajMpG9L8vASZILrDGVFx7C961kKl7/djjvgRjDsmmaSI3T0QTAKL9Obf6c9mm2iI5HitILT3jqZB24Wt4lzWe1AUURyNdISkT9Wq0FAXQo3sGml9zqCVZzCNqO9jwJj1IUGok9pc8S+TWoMGcH5Jsc+jykZqKOVCcWWUzGHlLkG9ocVkFQIrGFigvU9eroR0QW+B4xBW990xCVSJ0TEcQPWBUPPfpn+uiX7qa047dEYWKRWg9NWr+/pM3TdaEMAyPVwKquKqsxCHfboZDMeZDWNQ68Orv9X3eR8i1Wr2qwqc=
  file_glob: true
  file: "*.dmg"
  on:
    tags: true
    repo: iNZightVIT/mac-installer
